org: yaritzalopez
service: api-alumnos

provider:
  name: aws
  runtime: python3.13
  timeout: 20 
  iam:
    role: arn:aws:iam::635391287019:role/LabRole

functions:
  listar:
    handler: ListarAlumnos.lambda_handler
    events:
      - http:
          path: /alumnos/listar
          method: post
          cors: true
          integration: lambda
  crear:
    handler: CrearAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/crear
          method: post
          cors: true
          integration: lambda
  buscar:
    handler: BuscarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/buscar
          method: post
          cors: true
          integration: lambda
  modificar:
    handler: ModificarAlumno.lambda_handler
    events:
      - http: 
          path: /alumnos/modificar
          method: post
          cors: true
          integration: lambda
  eliminar:
    handler: EliminarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/eliminar
          method: post
          cors: true
          integration: lambda
